name: multi-agent-pso
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip>=24
  - networkx>=3
  - rdkit
  - pip:
      - pyscf==2.9.0
      - geometric==1.1.1
variables:
  PYTHONNOUSERSITE: "1"
